version: '3'
services:
  mongodb-app:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ~/mongodb:/data/db

  server:
    image: sandy8169/kanban-backend
    ports:
      - 8080:8080
    depends_on:
      - mongodb-app

  messaging_app:
    image: sandy8169/messaging-app
    ports:
      - 4000:4000
    depends_on:
      - mongodb-app

  client:
    container_name: client-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    env_file:
      - .env
    depends_on:
      - server
      - messaging_app

volumes:
  mongodb:
